<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Test case started]]>
    </line>
    <line>
      <![CDATA[Test case is falied]]>
    </line>
    <line>
      <![CDATA[Test case started]]>
    </line>
    <line>
      <![CDATA[Test case is skipped]]>
    </line>
    <line>
      <![CDATA[Test case execution done]]>
    </line>
  </reporter-output>
  <suite started-at="2025-05-02T10:52:13 IST" name="Default suite" finished-at="2025-05-02T10:52:23 IST" duration-ms="10708">
    <groups>
    </groups>
    <test started-at="2025-05-02T10:52:13 IST" name="Default test" finished-at="2025-05-02T10:52:23 IST" duration-ms="10708">
      <class name="class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners">
        <test-method signature="testcase1()[pri:0, instance:class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners@11392934]" started-at="2025-05-02T10:52:13 IST" name="testcase1" finished-at="2025-05-02T10:52:23 IST" duration-ms="10615" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase1(TestCaseforListeners.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case started]]>
            </line>
            <line>
              <![CDATA[Test case is falied]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method signature="testcase2()[pri:0, instance:class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners@11392934]" started-at="2025-05-02T10:52:23 IST" name="testcase2" finished-at="2025-05-02T10:52:23 IST" depends-on-methods="class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase1" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase2() on instance class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners@11392934 depends on not successfully finished methods 
[class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase1() on instance class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners@11392934]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase2() on instance class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners@11392934 depends on not successfully finished methods 
[class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners.testcase1() on instance class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners@11392934]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Test case is skipped]]>
            </line>
            <line>
              <![CDATA[Test case execution done]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase2 -->
      </class> <!-- class_62_Reporter.log_Listeners_In_TestNG.TestCaseforListeners -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
